# Generated by Django 3.0.6 on 2020-05-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anjaliyeole', '0002_auto_20200526_0025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Awards',
            new_name='Award',
        ),
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='Interactions',
            new_name='Interaction',
        ),
    ]
