# Generated by Django 3.0.4 on 2020-05-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anjaliyeole', '0003_auto_20200526_0045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AreasofExpertise',
        ),
        migrations.DeleteModel(
            name='Award',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Interaction',
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default=0, upload_to='static'),
            preserve_default=False,
        ),
    ]
