# Generated by Django 3.0.4 on 2020-05-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anjaliyeole', '0004_auto_20200526_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='static/awards')),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('published', models.DateField(auto_now=True)),
                ('picture', models.ImageField(max_length=255, null=True, upload_to='static/books')),
                ('buy_link', models.URLField(default='default')),
            ],
        ),
    ]
