# Generated by Django 3.0.4 on 2020-05-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anjaliyeole', '0007_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='category',
            field=models.CharField(choices=[('CD', 'Curriculum Development'), ('PR', 'Papers Reviewed'), ('OM', 'Other Memberships'), ('PM', 'Professional Memberships'), ('BR', 'Books Reviewed'), ('TE', 'Teaching Experience')], max_length=200),
        ),
    ]
