# Generated by Django 3.0.4 on 2020-05-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anjaliyeole', '0008_auto_20200526_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='category',
            field=models.CharField(max_length=200),
        ),
    ]
