# Generated by Django 3.0.4 on 2020-05-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anjaliyeole', '0010_contactme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CE', 'Certifications'), ('PU', 'Publications'), ('CO', 'Copyrights'), ('PA', 'Patents'), ('PR', 'Projects'), ('WE', 'Webinars'), ('AR', 'Articles')], max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
