# Generated by Django 3.0.4 on 2020-05-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anjaliyeole', '0011_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='link',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='name',
        ),
    ]
