# Generated by Django 3.0.4 on 2020-05-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anjaliyeole', '0012_auto_20200526_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('Certifications', 'Certifications'), ('Publications', 'Publications'), ('Copyrights', 'Copyrights'), ('Patents', 'Patents'), ('Projects', 'Projects'), ('Webinars', 'Webinars'), ('Articles', 'Articles')], max_length=200),
        ),
    ]
