# Generated by Django 3.0.7 on 2020-06-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anjaliyeole', '0013_auto_20200526_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='contactme',
            options={'verbose_name': 'ContactMe', 'verbose_name_plural': 'ContactMe'},
        ),
    ]
